
name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/coding-standards.yml"
      - "composer.*"
      - "src/**" # but some packages use lib
      - "phpcs.xml.dist"
      - "tests/**"
  push:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/coding-standards.yml"
      - "composer.*"
      - "src/**" # but some packages use lib
      - "phpcs.xml.dist"
      - "tests/**"

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@use_a_valid_ref_here"
    with:
      php-version: "6.0" # use a custom version of PHP
