name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/continuous-integration.yml"
      - "composer.*"
      - "src/**" # but some packages use lib
      - "phpunit.xml.dist"
      - "tests/**"
  push:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/continuous-integration.yml"
      - "composer.*"
      - "src/**" # but some packages use lib
      - "phpunit.xml.dist"
      - "tests/**"

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/continuous-integration.yml@use_a_valid_ref_here"
    with:
      php-versions: '["6.0", "6.1"]' # Use custom versions of PHP
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

  phpunit-unstable-symfony:
    name: "PHPUnit with unstable Symfony"
    uses: "doctrine/.github/.github/workflows/continuous-integration-symfony-unstable.yml@use_a_valid_ref_here"
    with:
      php-versions: '["6.0"]' # Use custom version of PHP
      symfony-version-constraint: "47.1.x"

      # If the package requires some components but does not allow that version yet
      extra-requirements: "symfony/framework-bundle 47.1.x symfony/console 47.1.x"
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
