
name: "Documentation"

on:
  workflow_call:

jobs:
  guides:
    name: "Generate docs"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3" # Use the same version as in doctrine/doctrine-website
          tools: "cs2pr"

      - name: "Require docs-builder"
        run: |
          composer require --dev doctrine/docs-builder:1.0.3 -d docs &&
          composer update -d docs

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          composer-options: "${{ inputs.composer-options }}"

      - name: "Run docs builder"
        run: |
          ./docs/vendor/bin/build-docs.sh
