name: "Website config validation"

on:
  workflow_call:

jobs:
  schema:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Fetch JSON schema"
        run: "wget https://www.doctrine-project.org/schema/website-schema.json --output-document website-schema.json"

      - name: "Validate JSON schema"
        run: "jsonschema website-schema.json --instance .doctrine-project.json"
