name: "Website config validation"

on:
  workflow_call:
    inputs:
      json-file:
        description: "The path to the .doctrine-project.json file"
        default: ".doctrine-project.json"
        required: false
        type: "string"

jobs:
  schema:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Validate JSON schema"
        run: "jsonschema website-schema.json -i ${{ inputs.json-file }}"
